version: "3"
services:
    php:
        build: .
        ports:
            - 80:80
        restart: always
        volumes:
            - ./:/var/www/html/
            - ./:/etc/apache2/sites-enabled

    db:
        image: mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            - MYSQL_DATABASE=___base_name___
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
